### ISSUE TITLE
WebEid.Security missing

### ISSUE THREAD

**Issue by ShinMinRin** [web-eid/web-eid-asp-dotnet-example#10]
Hi everyone,

Sorry if it's not really an issue, I am kind of beginner here.
I am trying to build the example but VS is telling me that an error occured. I can't find how to resolve it.

Here is the error : 
"error NU1101 : unable to find package "WebEid.Security"  "

But I can't find this package anywhere, even there...

Please help me

**Comment by rborosak** [comment]
Can we please reopen this? 
The problem is still present
